### ISSUE TITLE
Нужна помощь

### ISSUE THREAD

**Issue by AleksandrNagovitsyn** [AleksandrNagovitsyn/CivilCodex#1]
@coursar

1. В тревисе мой репозиторий на добавляется. Остальные добавляет, а именно этот не видит 
![изображение](https://user-images.githubusercontent.com/55318485/69861652-db863480-12a9-11ea-9060-4a708569e068.png)

2. Приложение на хероку не запускается, вот лог 
![изображение](https://user-images.githubusercontent.com/55318485/69858186-885cb380-12a2-11ea-8658-aaf3e18ea714.png)

UPD: В общем заработал, я установил heroku CLI, потыкал в командной строке, куда-то клонировал гитхабовский репозиторий и изменил procfile. Что из этого помогло, не знаю.  Но полагаю то, что я связал приложение с гитхабом ,а не с тревисом. 

3. За что отвечает файл procfile? Как я в дальнейшем буду знать что туда писать? 
https://github.com/AleksandrNagovitsyn/CivilCodex/blob/411bc2bfb9c303c8a4893d6c6079951157f58533/Procfile#L1

4. Для чего вообще нужен trvis ci, если простыми словами? 

5. Можно ли без travis запуститься на хероку? 

6. Для чего нужна переменная окружения и как правильно ей путь прописывать? Весь путь на локальном диске? 

**По Сервлетам**

7. манипуляции с getatribute вообще не понял. Зачем в сервелете устанавливать атрибут, а здесь его получать? Что дают эти перебросы? Приложение и без этого функционирует
https://github.com/AleksandrNagovitsyn/CivilCodex/blob/411bc2bfb9c303c8a4893d6c6079951157f58533/src/main/webapp/WEB-INF/Rental.jsp#L25

8. как здесь программа понимает откуда брать этот параметр? Просто ищет соответствующие название ключа в гет запросе или в названиях полей input?
https://github.com/AleksandrNagovitsyn/CivilCodex/blob/411bc2bfb9c303c8a4893d6c6079951157f58533/src/main/java/ru/itpark/servlet/HousingRentalServlet.java#L78

**Comment by coursar** [comment]
1. Там есть кнопка Sync Now - нажмите её, посмотрите на результат
1. `UPLOAD_PATH=/app/upload` должно быть без пробелов
1. Procfile отвечает за то, как запускать ваше приложение. Мы брали то, что подходит для нашего приложения - разъяснялось на лекции. Если материалов лекции недостаточно, то нужно смотреть сюда: https://devcenter.heroku.com/articles/procfile, https://devcenter.heroku.com/articles/java-webapp-runner
1. Нужен для того, чтобы за вас собрать приложение, прогнать на нём проверки (если они есть) и развернуть на Heroku (см. https://onagile.ru/industries/software-development/continuous-delivery)
1. Можно
1. Чтобы жёстко не вшивать в приложение путь (т.к. путь на вашем копьютере и на Heroku будет отличаться). Правильно: локально пишете полный путь до каталога, на Heroku - /app/upload (если хотите указать на тот каталог, который лежит у вас в GitHub)
1. Уберите и посмотрите, что изменится. Атрибуты - способ передачи данных между Сервлетами (а JSP-страница это тоже сервлет)
1. Ищет в параметрах запроса (для GET они будут в query запроса, попадают они туда либо если вы их ввели руками, либо если отправили форму с полем имя которой равно `search`). Есть и другие способы отправить, например, JS - но мы их не рассматривали.
